version: '3.4'

services:
  rabbit:
    image: 'rabbitmq:3.6-management-alpine'
    hostname: "rabbit"
    environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: "guest"
        RABBITMQ_DEFAULT_PASS: "guest"
        RABBITMQ_DEFAULT_VHOST: "/"
    ports:
    - "5672:5672"
    - "15672:15672"
    labels:
        NAME: "rabbitmq"

  #consumer:
  #  image: ${DOCKER_REGISTRY-}consumer
  #  build:
  #    context: .
  #    dockerfile: Consumer/Dockerfile

  #publisher:
  #  image: ${DOCKER_REGISTRY-}publisher
  #  build:
  #    context: .
  #    dockerfile: Publisher/Dockerfile